Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2020-10, with the labels that each got.

#126 [docs][installation] Add FSL Prelude as dependency
  README.md
  docs/source/2_getting_started/1_installation.rst
Labels: Priority:HIGH, card:TO_REVIEW, documentation

#124 Optimizing optimizer code to run faster on large fieldmaps with small masks
  shimmingtoolbox/optimizer/basic_lsq.py
  shimmingtoolbox/optimizer/basic_optimizer.py
Labels: enhancement, refactoring

#131 Update __dir_testing__ to be an absolute path
  examples/general_demo.py
  shimmingtoolbox/__init__.py
Labels: card:TO_REVIEW, enhancement

#132 fix remove_tmp argument in dicom_to_nifti
  shimmingtoolbox/dicom_to_nifti.py
  test/test_dicom_to_nifti.py
Labels: bug, card:TO_REVIEW

#138 Updates link for testing-data
  shimmingtoolbox/cli/download_data.py
Labels: card:TO_REVIEW

#120 Update dicom_to_nifti with a CLI
  config/dcm2bids.json
  setup.py
  shimmingtoolbox/cli/dicom_to_nifti.py
  test/cli/test_cli_dicom_to_nifti.py
  test/test_dicom_to_nifti.py
Labels: card:TO_REVIEW, enhancement

#141 Fixed biot-savart scaling
  shimmingtoolbox/coils/biot_savart.py
  test/test_biot_savart.py
Labels: hacktoberfest-accepted

#129 Optimizer improvements
  shimmingtoolbox/optimizer/basic_lsq.py
  shimmingtoolbox/optimizer/basic_optimizer.py
  shimmingtoolbox/optimizer/lsq_optimizer.py
  shimmingtoolbox/optimizer/sequential.py
Labels: enhancement, hacktoberfest-accepted, refactoring

#136 Ensure test environment is set up with test data and soft dependencies before running tests
  .travis.yml
  conftest.py
  docs/source/2_getting_started/1_installation.rst
  pytest.ini
  test/cli/test_cli_dicom_to_nifti.py
  test/test_dicom_to_nifti.py
  test/test_prelude.py
Labels: card:TO_REVIEW, question, testing

#146 Update shimming-toolbox package install
  .travis.yml
  setup.py
  shimmingtoolbox/cli/__init__.py
Labels: installation

#142 Add ability to read from the PMU
  shimmingtoolbox/pmu.py
  test/test_pmu.py
Labels: feature

#150 Add ShellCheck to Travis build
  .travis.yml
Labels: testing

#153 Remove unneeded example modules
  docs/source/6_api_reference/api.rst
  setup.py
  shimmingtoolbox/b0map.py
  shimmingtoolbox/cli/b0map.py
  shimmingtoolbox/cli/referencemaps.py
  shimmingtoolbox/referencemaps.py
Labels: refactoring

#149 Add ability to get timing data from scans
  shimmingtoolbox/cli/download_data.py
  shimmingtoolbox/load_nifti.py
  shimmingtoolbox/utils.py
  test/test_pmu.py
Labels: feature, hacktoberfest-accepted
