Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2020-09, with the labels that each got.

#74 Create synthetic coil-profiles
  .gitignore
  docs/source/6_api_reference/api.rst
  shimmingtoolbox/coils/__init__.py
  shimmingtoolbox/coils/siemens_basis.py
  shimmingtoolbox/coils/spherical_harmonics.py
  test/test_siemens_basis.py
  test/test_spherical_harmonics.py
Labels: feature

#78 Repair dicom_to_nifti missing calls [bug]
  shimmingtoolbox/dicom_to_nifti.py
Labels: bug

#90 [chore][cli/download_data] Remove stale TODO
  shimmingtoolbox/cli/download_data.py
Labels: card:TO_REVIEW, fix:path

#93 [fix][download_data] Automatically generate dataset info in CLI help message
  shimmingtoolbox/cli/download_data.py
Labels: card:TO_REVIEW, enhancement, fix:minor

#103 Update minimum version to Python 3.7
  docs/source/2_getting_started/1_installation.rst
  readthedocs.yml
  setup.py
Labels: installation

#104 Fix link to installation instructions
  README.md
Labels: installation

#97 Moved testing and docs packages in default installation
  docs/source/2_getting_started/1_installation.rst
  setup.py
Labels: card:TO_REVIEW, installation

#107 Satisfy GitHub community profile checklist
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/contributing.md
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  docs/source/3_contributing/CONTRIBUTING.rst
Labels: card:TO_REVIEW, documentation

#73 Implementing basic optimizer and test bench
  shimmingtoolbox/coils/biot_savart.py
  shimmingtoolbox/optimizer/__init__.py
  shimmingtoolbox/optimizer/basic_lsq.py
  shimmingtoolbox/optimizer/basic_optimizer.py
  shimmingtoolbox/optimizer/sequential.py
  test/test_biot_savart.py
  test/test_sequential_zslice.py
Labels: card:TO_REVIEW, feature

#111 Updated URL for download data testing
  shimmingtoolbox/cli/download_data.py
Labels: enhancement

#115 Update repo name in documentation and project config files
  docs/Makefile
  docs/source/2_getting_started/1_installation.rst
  docs/source/2_getting_started/2_getting_started.rst
  docs/source/2_getting_started/3_help.rst
  docs/source/3_contributing/CONTRIBUTING.rst
  docs/source/3_contributing/contributors.rst
  docs/source/4_about/license.rst
  docs/source/conf.py
  setup.py
Labels: Priority:HIGH, card:TO_REVIEW, documentation
