Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2020-11, with the labels that each got.

#168 Update generate meshgrid
  shimmingtoolbox/coils/coordinates.py
  test/test_coordinates.py
  test/test_siemens_basis.py
Labels: bug

#171 Fix read_nii not looking for ImageComments and ImageType
  shimmingtoolbox/load_nifti.py
  test/test_load_nifti.py
Labels: bug

#175 Fix singleton on last dimension error in prelude
  shimmingtoolbox/unwrap/prelude.py
  test/test_prelude.py
Labels: bug

#166 Add documentation stub for dicom_to_nifti.py
  docs/source/6_api_reference/api.rst
  shimmingtoolbox/cli/dicom_to_nifti.py
Labels: documentation

#178 Change prelude mag parameter to be an optional argument
  examples/general_demo.py
  shimmingtoolbox/unwrap/prelude.py
  test/test_prelude.py
Labels: refactoring

#169 Add ability to create fieldmaps
  setup.py
  shimmingtoolbox/cli/prepare_fieldmap.py
  shimmingtoolbox/prepare_fieldmap.py
  shimmingtoolbox/unwrap/unwrap_phase.py
  test/cli/test_cli_prepare_fieldmap.py
  test/test_prepare_fieldmap.py
  test/test_unwrap_phase.py
Labels: feature

#182 Add GitHub Actions CI builds
  .github/tests.yml
  README.md
  ci.sh
Labels: card:TO_REVIEW, testing

#181 Compute gradient in physical and voxel coordinate systems
  shimmingtoolbox/coils/coordinates.py
  test/test_coordinates.py
Labels: enhancement

#179 Fix local error with load_nifti
  shimmingtoolbox/load_nifti.py
  test/test_load_nifti.py
Labels: bug

#185 Create new CLI documentation section
  docs/source/6_cli_reference/cli.rst
  docs/source/7_api_reference/api.rst
  docs/source/index.rst
Labels: card:TO_REVIEW, documentation

#176 Check installation and versions of 3rd party binaries
  conftest.py
  docs/source/6_cli_reference/cli.rst
  setup.py
  shimmingtoolbox/cli/check_env.py
  test/cli/test_check_env.py
Labels: card:TO_REVIEW, feature, refactoring
