Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2020-12, with the labels that each got.

#183 Add GitHub Actions CI builds
  .github/workflows/tests.yml
  .travis.yml
  README.md
  ci.sh
Labels: card:TO_REVIEW, testing

#147 Fix RTD badge
  README.md
Labels: documentation

#189 Update prepare fieldmap
  shimmingtoolbox/cli/prepare_fieldmap.py
  test/cli/test_cli_prepare_fieldmap.py
Labels: bug, enhancement, refactoring

#137 Add square, cube and threshold to cli
  docs/source/6_cli_reference/cli.rst
  docs/source/conf.py
  setup.py
  shimmingtoolbox/cli/mask.py
  test/cli/test_cli_mask.py
Labels: feature

#191 Rename phasediff image in dicom_to_nifti
  shimmingtoolbox/dicom_to_nifti.py
  test/test_dicom_to_nifti.py
Labels: enhancement

#195 Update download data link
  shimmingtoolbox/cli/download_data.py
Labels: testing

#134 Realtime_zshim shim CLI
  setup.py
  shimmingtoolbox/cli/realtime_zshim.py
  shimmingtoolbox/coils/coordinates.py
  shimmingtoolbox/pmu.py
  shimmingtoolbox/shim/__init__.py
  shimmingtoolbox/shim/realtime_zshim.py
  test/cli/test_cli_realtime_zshim.py
  test/shim/test_realtime_zshim.py
  test/test_coordinates.py
  test/test_pmu.py
Labels: feature

#197 Implementation of a test to verify the correct creation of the mask
  shimmingtoolbox/cli/mask.py
  test/cli/test_cli_mask.py
Labels: enhancement

#92 Added example shell script for realtime z-shimming
  config/dcm2bids.json
  examples/demo_realtime_zshimming.sh
  examples/realtime_zshimming.sh
  shimmingtoolbox/coils/coordinates.py
  shimmingtoolbox/load_nifti.py
  shimmingtoolbox/shim/realtime_zshim.py
  shimmingtoolbox/utils.py
  test/shim/test_realtime_zshim.py
Labels: Epic, card:DESIGN_DISCUSSION, enhancement
