Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2021-01, with the labels that each got.

#202 Remove extraneous workflow
  .github/tests.yml
Labels: testing

#203 Add the Twitter badge
  README.md
Labels: documentation

#207 Fix coveralls 3.0.0 bug and github actions macos 11.0 bug
  .github/workflows/tests.yml
Labels: bug

#184 Installation of the SpinalCord Toolbox on GH Actions
  .github/workflows/tests.yml
Labels: feature, testing
