Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2021-02, with the labels that each got.

#215 ci: Add pre-commit configs
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  docs/source/contributing/CONTRIBUTING.rst
  docs/source/getting_started/installation.rst
  setup.py
Labels: card:TO_REVIEW, installation

#225 Cache SCT in GitHub Actions CI workflow
  .github/workflows/tests.yml
Labels: testing

#223 CI: Check for correct EOF
  .pre-commit-config.yaml
  examples/demo_realtime_zshimming.sh
  examples/general_demo.py
  examples/realtime_zshimming.sh
  shimmingtoolbox/cli/download_data.py
  shimmingtoolbox/download.py
  test/cli/test_cli_prepare_fieldmap.py
  test/test_example_scripts.py
Labels: installation

#224 ci: Check for end-of-line trailing whitespace
  .pre-commit-config.yaml
  docs/source/contributing/CONTRIBUTING.rst
  examples/volume_RT_shim_respiratory.py
  shimmingtoolbox/coils/biot_savart.py
  shimmingtoolbox/optimizer/basic_optimizer.py
  shimmingtoolbox/optimizer/lsq_optimizer.py
  shimmingtoolbox/shim/realtime_zshim.py
  shimmingtoolbox/simulate/numerical_model.py
Labels: installation

#226 Update download_data link to the latest release
  shimmingtoolbox/cli/download_data.py
Labels: testing

#200 eao/gaussian-filter
  shimmingtoolbox/cli/prepare_fieldmap.py
  shimmingtoolbox/prepare_fieldmap.py
  shimmingtoolbox/shim/realtime_zshim.py
  test/cli/test_cli_prepare_fieldmap.py
  test/test_prepare_fieldmap.py
Labels: feature

#221 Add RIRO and Static masks to realtime zshimming
  examples/demo_realtime_zshimming.sh
  shimmingtoolbox/cli/realtime_zshim.py
  shimmingtoolbox/shim/realtime_zshim.py
  test/cli/test_cli_realtime_zshim.py
  test/shim/test_realtime_zshim.py
Labels: enhancement

#231 Update docs and readme for new dcm2niix version
  README.md
  docs/source/getting_started/installation.rst
Labels: documentation
