Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2021-06, with the labels that each got.

#275 Refactored prelude and dcm2niix to avoid bug when not on PATH
  .github/workflows/tests.yml
  conftest.py
  shimmingtoolbox/cli/check_env.py
  test/cli/test_check_env.py
Labels: bug

#277 Update API and CLI documentation
  docs/source/api_reference/api.rst
  docs/source/cli_reference/cli.rst
  examples/demo_realtime_shimming.sh
  examples/realtime_shimming.sh
  shimmingtoolbox/cli/dicom_to_nifti.py
  shimmingtoolbox/cli/download_data.py
  shimmingtoolbox/cli/image.py
  shimmingtoolbox/cli/mask.py
  shimmingtoolbox/cli/maths.py
  shimmingtoolbox/cli/prepare_fieldmap.py
  shimmingtoolbox/cli/realtime_shim.py
  shimmingtoolbox/coils/biot_savart.py
  shimmingtoolbox/pmu.py
  shimmingtoolbox/shim/realtime_shim.py
  test/cli/test_cli_dicom_to_nifti.py
  test/cli/test_cli_mask.py
  test/cli/test_cli_prepare_fieldmap.py
  test/cli/test_cli_realtime_shim.py
Labels: documentation, refactoring

#253 Refactor and add features to Optimizers
  docs/source/api_reference/api.rst
  shimmingtoolbox/coils/coil.py
  shimmingtoolbox/coils/coordinates.py
  shimmingtoolbox/optimizer/basic_optimizer.py
  shimmingtoolbox/optimizer/lsq_optimizer.py
  shimmingtoolbox/optimizer/sequential.py
  test/test_coil.py
  test/test_sequential_zslice.py
Labels: enhancement, refactoring

#276 Addition of the commands accessible in shimming-toolbox in the README.rst
  README.rst
Labels: documentation
