Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2022-03, with the labels that each got.

#353 Fix st_b0shim realtime-dynamic order 0 and output folder for masking and fieldmap
  shimmingtoolbox/cli/b0shim.py
  shimmingtoolbox/cli/mask.py
  shimmingtoolbox/cli/prepare_fieldmap.py
  test/cli/test_cli_b0shim.py
Labels: bug

#362 Update required importlib-metadata version
  setup.py
Labels: fix:minor

#348 Simplify installation documentation
  docs/source/cli_reference/cli.rst
  docs/source/getting_started/flowchart.rst
  docs/source/getting_started/getting_started.rst
  docs/source/getting_started/installation_gui.rst
  docs/source/getting_started/installation_st.rst
  docs/source/getting_started/installation_st/linux.rst
  docs/source/getting_started/installation_st/mac.rst
  docs/source/index.rst
  docs/source/user_section/help.rst
  docs/source/user_section/installation.rst
  docs/source/user_section/tutorials.rst
  docs/source/user_section/tutorials/shell_script.rst
  examples/README.rst
  installer/create_venv.sh
  installer/install_shimming_toolbox.sh
Labels: documentation

#366 Add GUI example tuto for b1 shim
  docs/source/user_section/tutorials.rst
  docs/source/user_section/tutorials/b1_shimming.rst
  shimmingtoolbox/cli/download_data.py
Labels: documentation
