Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2022-02, with the labels that each got.

#339 Add gradient shimming output file format to the b0 static CLI
  shimmingtoolbox/cli/b0shim.py
  test/cli/test_cli_b0shim.py
Labels: enhancement

#333 Minor improvements of B1+ shimming functionalities
  shimmingtoolbox/cli/b1shim.py
  shimmingtoolbox/load_nifti.py
  shimmingtoolbox/shim/b1shim.py
  shimmingtoolbox/utils.py
  test/cli/test_cli_b1shim.py
  test/shim/test_b1shim.py
Labels: enhancement

#338 Update st_dicom_to_nifti help
  shimmingtoolbox/cli/dicom_to_nifti.py
  shimmingtoolbox/dicom_to_nifti.py
  test/cli/test_cli_dicom_to_nifti.py
Labels: refactoring

#344 Fix B1+ maps right after their conversion into NIfTI
  shimmingtoolbox/cli/b1shim.py
  shimmingtoolbox/cli/dicom_to_nifti.py
  shimmingtoolbox/cli/download_data.py
  shimmingtoolbox/dicom_to_nifti.py
  shimmingtoolbox/load_nifti.py
  shimmingtoolbox/masking/threshold.py
  shimmingtoolbox/shim/b1shim.py
  test/cli/test_cli_b1shim.py
  test/cli/test_cli_dicom_to_nifti.py
  test/shim/test_b1shim.py
  test/test_dicom_to_nifti.py
  test/test_load_nifti.py
Labels: enhancement

#346 Solve launchers needing to be launched from the ST venv
  shimmingtoolbox/dicom_to_nifti.py
  shimmingtoolbox/utils.py
Labels: bug

#335 Improve output of st_b0shim
  config/dcm2bids.json
  shimmingtoolbox/cli/b0shim.py
  shimmingtoolbox/cli/image.py
  shimmingtoolbox/masking/mask_utils.py
  shimmingtoolbox/prepare_fieldmap.py
  shimmingtoolbox/shim/sequencer.py
  shimmingtoolbox/shim/shim_utils.py
  test/cli/test_cli_b0shim.py
  test/cli/test_cli_image.py
Labels: enhancement
