Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2023-04, with the labels that each got.

#445 Change ubuntu 18.04 to 22.04
  .github/workflows/tests.yml
Labels: testing

#447 Fix phasediff renaming issue for dual-echo fieldmaps
  shimmingtoolbox/dicom_to_nifti.py
  test/test_dicom_to_nifti.py
Labels: bug

#443 Make Resampling faster by using multiprocessing with joblib
  setup.py
  shimmingtoolbox/coils/coordinates.py
Labels: enhancement

#448 Resolve prelude error if --savemask directory is not already created when field mapping
  shimmingtoolbox/cli/prepare_fieldmap.py
  test/cli/test_cli_prepare_fieldmap.py
Labels: bug
