Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2023-08, with the labels that each got.

#467 Coil profiles creation from CAD geometries
  docs/source/cli_reference/cli.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/user_section/install.rst
  docs/source/user_section/tutorials.rst
  docs/source/user_section/tutorials/b0_dynamic_shimming.rst
  docs/source/user_section/tutorials/create_b0_coil_profiles.rst
  setup.py
  shimmingtoolbox/cli/create_coil_profiles.py
  shimmingtoolbox/cli/download_data.py
  shimmingtoolbox/coils/biot_savart.py
  shimmingtoolbox/coils/create_coil_profiles.py
  shimmingtoolbox/utils.py
  test/cli/test_cli_create_coil_profiles.py
Labels: feature

#458 Changed the optimizer to a quadratic problem
  setup.py
  shimmingtoolbox/cli/b0shim.py
  shimmingtoolbox/optimizer/basic_optimizer.py
  shimmingtoolbox/optimizer/lsq_optimizer.py
  shimmingtoolbox/optimizer/optimizer_utils.py
  shimmingtoolbox/optimizer/quadprog_optimizer.py
  shimmingtoolbox/shim/sequencer.py
  test/shim/test_sequencer.py
Labels: feature, Epic

#472 Update link to the newest version of the coil profile tutorial
  shimmingtoolbox/cli/download_data.py
Labels: enhancement

#477 Update nibabel to latest version
  setup.py
  shimmingtoolbox/cli/mask.py
  shimmingtoolbox/masking/threshold.py
  test/cli/test_cli_b0shim.py
  test/cli/test_cli_image.py
  test/cli/test_cli_mask.py
  test/cli/test_cli_realtime_shim.py
  test/masking/test_shape_threshold.py
  test/shim/test_sequencer.py
  test/test_load_nifti.py
Labels: enhancement

#462 Improve real-time shimming
  shimmingtoolbox/pmu.py
  shimmingtoolbox/shim/sequencer.py
  shimmingtoolbox/shim/shim_utils.py
  test/cli/test_cli_b0shim.py
Labels: enhancement
