Repository shimming-toolbox/shimming-toolbox, pull requests merged in 2024-01, with the labels that each got.

#499 Change phase range in field mapping calculations
  shimmingtoolbox/load_nifti.py
Labels: bug, Priority:HIGH

#484 Split coils and scaner order for optimization + alow specific scaner orders for each
  config/coil_config.json
  config/custom_coil_config.json
  shimmingtoolbox/cli/b0shim.py
  shimmingtoolbox/cli/create_coil_profiles.py
  shimmingtoolbox/cli/download_data.py
  shimmingtoolbox/coils/coil.py
  shimmingtoolbox/coils/spher_harm_basis.py
  shimmingtoolbox/optimizer/basic_optimizer.py
  shimmingtoolbox/shim/sequencer.py
  shimmingtoolbox/shim/shim_utils.py
  test/cli/test_cli_b0shim.py
  test/cli/test_cli_create_coil_profiles.py
  test/shim/test_sequencer.py
  test/shim/test_shim_utils.py
  test/test_coil.py
  test/test_spher_harm_basis.py
Labels: enhancement, Priority:HIGH

#508 Upgrade to python 3.10
  installer/install_shimming_toolbox.sh
Labels: installation

#498 Implement Philips+GE related spherical harmonics conventions
  .gitignore
  installer/windows_install.bat
  shimmingtoolbox/coils/coil.py
  shimmingtoolbox/coils/create_coil_profiles.py
  shimmingtoolbox/coils/spher_harm_basis.py
  shimmingtoolbox/shim/sequencer.py
  shimmingtoolbox/shim/shim_utils.py
  shimmingtoolbox/utils.py
  test/test_coil.py
  test/test_spher_harm_basis.py
Labels: enhancement

#510 Bug fix: "absolute" output format
  shimmingtoolbox/cli/b0shim.py
  shimmingtoolbox/shim/shim_utils.py
  test/cli/test_cli_b0shim.py
Labels: bug

#512 Update custom coil config file
  config/custom_coil_config.json
  shimmingtoolbox/__init__.py
  shimmingtoolbox/cli/b0shim.py
  test/cli/test_cli_b0shim.py
Labels: bug
